"use strict";
// Exposes window.api to the renderer (async IPC). Replaces window.pywebview.api.
const { contextBridge, ipcRenderer, webUtils } = require("electron");
const invoke = (ch) => (...args) => ipcRenderer.invoke(ch, ...args);

contextBridge.exposeInMainWorld("sam", {  // window.sam (not window.api — that collides with app.js's `let api`)
  get_startup_file: invoke("get_startup_file"),
  open_dialog: invoke("open_dialog"),
  read_path: invoke("read_path"),
  save: invoke("save"),
  save_dialog: invoke("save_dialog"),
  set_title: invoke("set_title"),
  set_dirty: invoke("set_dirty"),
  set_on_top: invoke("set_on_top"),
  new_window: invoke("new_window"),
  close_window: invoke("close_window"),
  exit_app: invoke("exit_app"),
  minimize: invoke("minimize"),
  toggle_maximize: invoke("toggle_maximize"),
  load_settings: invoke("load_settings"),
  save_settings: invoke("save_settings"),
  add_recent: invoke("add_recent"),
  clear_recents: invoke("clear_recents"),
  app_info: invoke("app_info"),
  open_external: invoke("open_external"),
  restore: invoke("restore"),
  open_in_explorer: invoke("open_in_explorer"),
  set_default: invoke("set_default"),
  reset_settings: invoke("reset_settings"),
  stat_path: invoke("stat_path"),
  confirm_reload: invoke("confirm_reload"),
  add_dont_ask_reload: invoke("add_dont_ask_reload"),
  read_binary: invoke("read_binary"),
  flash_frame: invoke("flash_frame"),
  read_notes: invoke("read_notes"),
  write_notes: invoke("write_notes"),
  stat_notes: invoke("stat_notes"),
  handle_saved_notes: invoke("handle_saved_notes"),
  get_bounds: invoke("get_bounds"),
  set_position: invoke("set_position"),
  set_min_size: invoke("set_min_size"),
  set_opacity: invoke("set_opacity"),
  force_close: invoke("force_close"),
  set_pristine: invoke("set_pristine"),
  kick_focus: invoke("kick_focus"),
  onAskDialog: (cb) => ipcRenderer.on("ask-dialog", (e, id, spec) => cb(id, spec)),
  ask_dialog_reply: (id, result) => ipcRenderer.send("ask-dialog-reply", id, result),
  path_for_file: (file) => { try { return webUtils.getPathForFile(file); } catch (e) { return ""; } },  // Electron 33: File.path is gone
  onSettingsReset: (cb) => ipcRenderer.on("settings-reset", () => cb()),
  onConfirmClose: (cb) => ipcRenderer.on("confirm-close", () => cb()),
  jslog: (level, msg) => ipcRenderer.send("jslog", level, msg),
});
